-- MySQL Script generated by MySQL Workbench
-- Sat 19 Aug 2017 08:46:15 PM EAT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema harlerte_azimadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema harlerte_azimadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `harlerte_azimadb` DEFAULT CHARACTER SET utf8 ;
USE `harlerte_azimadb` ;

-- -----------------------------------------------------
-- Table `harlerte_azimadb`.`tblUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_azimadb`.`tblUsers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `othernames` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `idno` VARCHAR(10) NULL DEFAULT NULL,
  `dob` DATE NULL DEFAULT NULL,
  `imei` VARCHAR(20) NULL DEFAULT NULL,
  `loan_limit` FLOAT NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `date_created` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `harlerte_azimadb`.`tblLoanApplications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `harlerte_azimadb`.`tblLoanApplications` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NULL DEFAULT NULL,
  `apply_date` DATETIME NOT NULL,
  `due_date` DATETIME NOT NULL,
  `status` VARCHAR(15) NULL,
  `tblUsers_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tblUsers_id`),
  INDEX `fk_tblLoanApplications_tblUsers_idx` (`tblUsers_id` ASC),
  CONSTRAINT `fk_tblLoanApplications_tblUsers`
    FOREIGN KEY (`tblUsers_id`)
    REFERENCES `harlerte_azimadb`.`tblUsers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
